package me.kire.re.pojogenerator.application.dto.in;

/*
 * Generated by POJO generator https://pojo-generator.vercel.app
 */
public class DtoInGeneratePojoPost {
    private Boolean lombok;

    private String text;

    public Boolean getLombok() {
        return lombok;
    }

    public void setLombok(Boolean lombok) {
        this.lombok = lombok;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }
}
